# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_function_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(665, 178)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/logofox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet(" \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;\n"
"font-size: 18px")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 146, 31))
        self.label.setStyleSheet("border-color: none;")
        self.label.setObjectName("label")
        self.curr_data = QtWidgets.QCheckBox(Dialog)
        self.curr_data.setGeometry(QtCore.QRect(80, 20, 81, 21))
        self.curr_data.setTabletTracking(True)
        self.curr_data.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.curr_data.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.curr_data.setStyleSheet("font-size: 10px;\n"
"border-color: none")
        self.curr_data.setObjectName("curr_data")
        self.cat_l = QtWidgets.QLineEdit(Dialog)
        self.cat_l.setGeometry(QtCore.QRect(340, 40, 150, 25))
        self.cat_l.setStyleSheet("background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;\n"
"font-size:14px")
        self.cat_l.setObjectName("cat_l")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(170, 10, 146, 31))
        self.label_2.setStyleSheet("border-color: none;")
        self.label_2.setObjectName("label_2")
        self.type_c = QtWidgets.QComboBox(Dialog)
        self.type_c.setGeometry(QtCore.QRect(175, 40, 150, 26))
        self.type_c.setStyleSheet("background-color: rgba(255, 255, 255, 150);")
        self.type_c.setObjectName("type_c")
        self.type_c.addItem("")
        self.type_c.addItem("")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(340, 10, 146, 31))
        self.label_3.setStyleSheet("border-color: none;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(505, 10, 146, 31))
        self.label_4.setStyleSheet("border-color: none;")
        self.label_4.setObjectName("label_4")
        self.summa_l = QtWidgets.QLineEdit(Dialog)
        self.summa_l.setGeometry(QtCore.QRect(505, 40, 150, 25))
        self.summa_l.setStyleSheet("background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;\n"
"font-size:12")
        self.summa_l.setObjectName("summa_l")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 146, 31))
        self.label_5.setStyleSheet("border-color: none;")
        self.label_5.setObjectName("label_5")
        self.opis_l = QtWidgets.QLineEdit(Dialog)
        self.opis_l.setGeometry(QtCore.QRect(10, 100, 646, 26))
        self.opis_l.setStyleSheet("background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;\n"
"font-size:14px")
        self.opis_l.setObjectName("opis_l")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(635, 40, 21, 26))
        self.label_6.setStyleSheet("border-color: none;")
        self.label_6.setObjectName("label_6")
        self.add_hist = QtWidgets.QPushButton(Dialog)
        self.add_hist.setGeometry(QtCore.QRect(10, 135, 646, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_hist.sizePolicy().hasHeightForWidth())
        self.add_hist.setSizePolicy(sizePolicy)
        self.add_hist.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_hist.setStyleSheet("font-size: 17pt;\n"
"font-family: Neo Sans Pro;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,80);\n"
"border-radius: 7px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/logo/plus-dynamic-premium.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_hist.setIcon(icon1)
        self.add_hist.setIconSize(QtCore.QSize(100, 100))
        self.add_hist.setObjectName("add_hist")
        self.error = QtWidgets.QLabel(Dialog)
        self.error.setGeometry(QtCore.QRect(380, 70, 271, 26))
        self.error.setStyleSheet("color: red;\n"
"font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Neo Sans Pro;")
        self.error.setText("")
        self.error.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.error.setObjectName("error")
        self.data_l = QtWidgets.QDateTimeEdit(Dialog)
        self.data_l.setGeometry(QtCore.QRect(10, 41, 151, 26))
        self.data_l.setStyleSheet("border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;\n"
"font-size:14px;\n"
"color: rgb(0, 0, 0);")
        self.data_l.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.data_l.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.data_l.setCalendarPopup(True)
        self.data_l.setTimeSpec(QtCore.Qt.LocalTime)
        self.data_l.setObjectName("data_l")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавить в историю"))
        self.label.setText(_translate("Dialog", "Дата"))
        self.curr_data.setText(_translate("Dialog", "Текущая"))
        self.label_2.setText(_translate("Dialog", "Тип операции"))
        self.type_c.setItemText(0, _translate("Dialog", "Расходы"))
        self.type_c.setItemText(1, _translate("Dialog", "Пополнение"))
        self.label_3.setText(_translate("Dialog", "Категории"))
        self.label_4.setText(_translate("Dialog", "Сумма"))
        self.summa_l.setText(_translate("Dialog", "0"))
        self.label_5.setText(_translate("Dialog", "Описание"))
        self.label_6.setText(_translate("Dialog", "₽"))
        self.add_hist.setText(_translate("Dialog", "ДОБАВИТЬ"))
        self.data_l.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy, H:mm"))
