# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bank_login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 666)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("font-family: Vag World;")
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 666))
        self.background.setStyleSheet("")
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(":/logo/bg.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.LOGIN = QtWidgets.QFrame(Form)
        self.LOGIN.setGeometry(QtCore.QRect(20, 120, 300, 270))
        self.LOGIN.setStyleSheet("background-color: rgba(255, 255, 255, 30); \n"
"border: 2px solid rgba(255,255,255,40);\n"
"border-radius: 7px; \n"
"color: white;")
        self.LOGIN.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LOGIN.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LOGIN.setObjectName("LOGIN")
        self.label = QtWidgets.QLabel(self.LOGIN)
        self.label.setGeometry(QtCore.QRect(10, 0, 121, 41))
        self.label.setStyleSheet("color: white;\n"
"font-size: 11pt;\n"
"background-color: none;\n"
"border: none;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.LOGIN)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 121, 41))
        self.label_2.setStyleSheet("color: white;\n"
"font-size: 11pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_2.setObjectName("label_2")
        self.password_label = QtWidgets.QLineEdit(self.LOGIN)
        self.password_label.setGeometry(QtCore.QRect(10, 110, 280, 30))
        self.password_label.setStyleSheet("font-family: Neo Sans Pro;")
        self.password_label.setText("")
        self.password_label.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_label.setObjectName("password_label")
        self.error = QtWidgets.QLabel(self.LOGIN)
        self.error.setGeometry(QtCore.QRect(10, 140, 281, 30))
        self.error.setStyleSheet("color: red;\n"
"font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Neo Sans Pro;")
        self.error.setText("")
        self.error.setObjectName("error")
        self.contbtn = QtWidgets.QPushButton(self.LOGIN)
        self.contbtn.setGeometry(QtCore.QRect(10, 200, 280, 30))
        self.contbtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 #ff7c1a, stop:0.427447 #fa9f36, stop:1 #ff7d09);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius:7px;\n"
"font-size: 17px")
        self.contbtn.setObjectName("contbtn")
        self.regbtn = QtWidgets.QPushButton(self.LOGIN)
        self.regbtn.setGeometry(QtCore.QRect(10, 235, 280, 30))
        self.regbtn.setStyleSheet("color: white;\n"
"border: 1px solid #ff7d09;\n"
"border-radius:7px;\n"
"font-size: 16px")
        self.regbtn.setObjectName("regbtn")
        self.login_label = QtWidgets.QLineEdit(self.LOGIN)
        self.login_label.setGeometry(QtCore.QRect(10, 40, 280, 30))
        self.login_label.setStyleSheet("font-family: Neo Sans Pro;\n"
"font-size: 15px")
        self.login_label.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.login_label.setObjectName("login_label")
        self.rememba = QtWidgets.QCheckBox(self.LOGIN)
        self.rememba.setGeometry(QtCore.QRect(10, 169, 281, 31))
        self.rememba.setStyleSheet("color: white;\n"
"font-size: 11pt;\n"
"background-color: none;\n"
"border: none;")
        self.rememba.setObjectName("rememba")
        self.REGISTR = QtWidgets.QFrame(Form)
        self.REGISTR.setEnabled(True)
        self.REGISTR.setGeometry(QtCore.QRect(320, 120, 300, 381))
        font = QtGui.QFont()
        font.setFamily("Vag World")
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.REGISTR.setFont(font)
        self.REGISTR.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.REGISTR.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.REGISTR.setStyleSheet("background-color: rgba(255, 255, 255, 30); \n"
"border: 2px solid rgba(255,255,255,40);\n"
"border-radius: 7px; \n"
"color: white;")
        self.REGISTR.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.REGISTR.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.REGISTR.setObjectName("REGISTR")
        self.label_10 = QtWidgets.QLabel(self.REGISTR)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 161, 41))
        self.label_10.setStyleSheet("color: white;\n"
"font-size: 11pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_10.setObjectName("label_10")
        self.login_label_r = QtWidgets.QLineEdit(self.REGISTR)
        self.login_label_r.setGeometry(QtCore.QRect(10, 40, 280, 30))
        self.login_label_r.setStyleSheet("font-family: Neo Sans Pro;\n"
"font-size: 15px")
        self.login_label_r.setObjectName("login_label_r")
        self.label_11 = QtWidgets.QLabel(self.REGISTR)
        self.label_11.setGeometry(QtCore.QRect(10, 140, 121, 41))
        self.label_11.setStyleSheet("color: white;\n"
"font-size: 11pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_11.setObjectName("label_11")
        self.password_label_r = QtWidgets.QLineEdit(self.REGISTR)
        self.password_label_r.setGeometry(QtCore.QRect(10, 180, 280, 30))
        font = QtGui.QFont()
        font.setFamily("Neo Sans Pro")
        self.password_label_r.setFont(font)
        self.password_label_r.setStyleSheet("font-family: Neo Sans Pro;")
        self.password_label_r.setText("")
        self.password_label_r.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_label_r.setObjectName("password_label_r")
        self.error_r = QtWidgets.QLabel(self.REGISTR)
        self.error_r.setGeometry(QtCore.QRect(10, 275, 281, 31))
        self.error_r.setStyleSheet("color: red;\n"
"font-size: 11pt;\n"
"font-family: Neo Sans Pro;\n"
"background-color: none;\n"
"border: none;")
        self.error_r.setText("")
        self.error_r.setObjectName("error_r")
        self.contbtn_r = QtWidgets.QPushButton(self.REGISTR)
        self.contbtn_r.setGeometry(QtCore.QRect(10, 310, 280, 30))
        self.contbtn_r.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 #ff7c1a, stop:0.427447 #fa9f36, stop:1 #ff7d09);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius:7px;\n"
"font-size: 17px")
        self.contbtn_r.setObjectName("contbtn_r")
        self.backbtn = QtWidgets.QPushButton(self.REGISTR)
        self.backbtn.setGeometry(QtCore.QRect(10, 345, 280, 30))
        self.backbtn.setStyleSheet("color: white;\n"
"border: 1px solid #ff7d09;\n"
"border-radius:7px;\n"
"font-size: 16px")
        self.backbtn.setObjectName("backbtn")
        self.label_13 = QtWidgets.QLabel(self.REGISTR)
        self.label_13.setGeometry(QtCore.QRect(10, 205, 121, 41))
        self.label_13.setStyleSheet("color: white;\n"
"font-size: 11pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_13.setObjectName("label_13")
        self.password_label_rr = QtWidgets.QLineEdit(self.REGISTR)
        self.password_label_rr.setGeometry(QtCore.QRect(10, 245, 280, 30))
        self.password_label_rr.setStyleSheet("font-family: Neo Sans Pro;")
        self.password_label_rr.setText("")
        self.password_label_rr.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_label_rr.setObjectName("password_label_rr")
        self.label_12 = QtWidgets.QLabel(self.REGISTR)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 161, 41))
        self.label_12.setStyleSheet("color: white;\n"
"font-size: 11pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_12.setObjectName("label_12")
        self.username = QtWidgets.QLineEdit(self.REGISTR)
        self.username.setGeometry(QtCore.QRect(10, 110, 280, 30))
        self.username.setStyleSheet("font-family: Neo Sans Pro;\n"
"font-size: 15px")
        self.username.setText("")
        self.username.setObjectName("username")
        self.bug = QtWidgets.QPushButton(Form)
        self.bug.setGeometry(QtCore.QRect(10, 610, 50, 50))
        self.bug.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.bug.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/logo/bug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bug.setIcon(icon1)
        self.bug.setIconSize(QtCore.QSize(50, 50))
        self.bug.setObjectName("bug")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FOXBANK"))
        self.label.setText(_translate("Form", "Логин"))
        self.label_2.setText(_translate("Form", "Пароль"))
        self.contbtn.setText(_translate("Form", "Продолжить"))
        self.regbtn.setText(_translate("Form", "Зарегистрироваться"))
        self.login_label.setText(_translate("Form", "+7 (___) ___ - __ - __"))
        self.rememba.setText(_translate("Form", "Запомнить"))
        self.label_10.setText(_translate("Form", "Номер телефона"))
        self.login_label_r.setText(_translate("Form", "+7 (___) ___ - __ - __"))
        self.label_11.setText(_translate("Form", "Пароль"))
        self.contbtn_r.setText(_translate("Form", "Продолжить"))
        self.backbtn.setText(_translate("Form", "Назад"))
        self.label_13.setText(_translate("Form", "Пароль повторно"))
        self.label_12.setText(_translate("Form", "Имя"))
import wall