# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bank_suclog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(660, 980)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWhatsThis("")
        Dialog.setStyleSheet("")
        self.background = QtWidgets.QLabel(Dialog)
        self.background.setGeometry(QtCore.QRect(0, 0, 660, 980))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(":/wallpaper/1.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.timelab = QtWidgets.QLabel(Dialog)
        self.timelab.setGeometry(QtCore.QRect(30, 180, 600, 60))
        font = QtGui.QFont()
        font.setFamily("Stolzl")
        font.setPointSize(-1)
        self.timelab.setFont(font)
        self.timelab.setStyleSheet("font-family: Stolzl;\n"
"font-size:45px;\n"
"color: rgb(255, 255, 255);")
        self.timelab.setAlignment(QtCore.Qt.AlignCenter)
        self.timelab.setObjectName("timelab")
        self.name = QtWidgets.QLabel(Dialog)
        self.name.setGeometry(QtCore.QRect(30, 240, 600, 60))
        font = QtGui.QFont()
        font.setFamily("Stolzl")
        font.setPointSize(-1)
        self.name.setFont(font)
        self.name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name.setStyleSheet("font-family:Stolzl;\n"
"font-size:45px;\n"
"color: rgb(255, 255, 255);")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.background_2 = QtWidgets.QLabel(Dialog)
        self.background_2.setGeometry(QtCore.QRect(0, 0, 660, 980))
        self.background_2.setStyleSheet("background-color: rgba(0, 0, 0, 60);")
        self.background_2.setText("")
        self.background_2.setScaledContents(False)
        self.background_2.setObjectName("background_2")
        self.foxbank = QtWidgets.QLabel(Dialog)
        self.foxbank.setGeometry(QtCore.QRect(265, 20, 130, 130))
        self.foxbank.setText("")
        self.foxbank.setPixmap(QtGui.QPixmap(":/logo/logofox.png"))
        self.foxbank.setScaledContents(True)
        self.foxbank.setObjectName("foxbank")
        self.forlogin = QtWidgets.QLabel(Dialog)
        self.forlogin.setGeometry(QtCore.QRect(1000, 1000, 55, 16))
        self.forlogin.setObjectName("forlogin")
        self.background.raise_()
        self.background_2.raise_()
        self.timelab.raise_()
        self.name.raise_()
        self.foxbank.raise_()
        self.forlogin.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "FOXBANK"))
        self.timelab.setText(_translate("Dialog", "•"))
        self.name.setText(_translate("Dialog", "•"))
        self.forlogin.setText(_translate("Dialog", "TextLabel"))
import wall
