# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'didinga_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_daidengy(object):
    def setupUi(self, daidengy):
        daidengy.setObjectName("daidengy")
        daidengy.resize(320, 242)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(daidengy.sizePolicy().hasHeightForWidth())
        daidengy.setSizePolicy(sizePolicy)
        daidengy.setMinimumSize(QtCore.QSize(320, 242))
        daidengy.setMaximumSize(QtCore.QSize(320, 242))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        daidengy.setWindowIcon(icon)
        daidengy.setStyleSheet("")
        self.LOGIN = QtWidgets.QFrame(daidengy)
        self.LOGIN.setGeometry(QtCore.QRect(10, 10, 300, 221))
        self.LOGIN.setStyleSheet("background-color: rgba(200, 200, 200, 80); \n"
"border: 2px solid rgba(200,200,200, 85);\n"
"border-radius: 7px; \n"
"font-family: Vag World;\n"
"")
        self.LOGIN.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LOGIN.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LOGIN.setObjectName("LOGIN")
        self.label = QtWidgets.QLabel(self.LOGIN)
        self.label.setGeometry(QtCore.QRect(10, 0, 271, 41))
        self.label.setStyleSheet("font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Vag World;")
        self.label.setObjectName("label")
        self.error = QtWidgets.QLabel(self.LOGIN)
        self.error.setGeometry(QtCore.QRect(10, 140, 281, 30))
        self.error.setStyleSheet("color: red;\n"
"font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Neo Sans Pro;")
        self.error.setText("")
        self.error.setObjectName("error")
        self.contbtn = QtWidgets.QPushButton(self.LOGIN)
        self.contbtn.setGeometry(QtCore.QRect(10, 180, 280, 30))
        self.contbtn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(166,255,0,1), stop:0.427447 rgba(16,255,0,1));\n"
"border: 1px solid rgba(255,255,255,40);\n"
"\n"
"border-radius:7px;\n"
"font-size: 17px")
        self.contbtn.setObjectName("contbtn")
        self.cardnum_label = QtWidgets.QLineEdit(self.LOGIN)
        self.cardnum_label.setGeometry(QtCore.QRect(10, 40, 280, 30))
        self.cardnum_label.setStyleSheet("font-family: Neo Sans Pro;\n"
"font-size: 17px")
        self.cardnum_label.setText("")
        self.cardnum_label.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cardnum_label.setObjectName("cardnum_label")
        self.summa_label = QtWidgets.QLineEdit(self.LOGIN)
        self.summa_label.setGeometry(QtCore.QRect(10, 110, 280, 30))
        self.summa_label.setStyleSheet("font-family: Neo Sans Pro;\n"
"font-size: 17px")
        self.summa_label.setText("")
        self.summa_label.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.summa_label.setObjectName("summa_label")
        self.label_4 = QtWidgets.QLabel(self.LOGIN)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 281, 41))
        self.label_4.setStyleSheet("font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Vag World;")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(daidengy)
        QtCore.QMetaObject.connectSlotsByName(daidengy)

    def retranslateUi(self, daidengy):
        _translate = QtCore.QCoreApplication.translate
        daidengy.setWindowTitle(_translate("daidengy", "FOXBANK"))
        self.label.setText(_translate("daidengy", "Номер карты другого банка"))
        self.contbtn.setText(_translate("daidengy", "Пополнить"))
        self.label_4.setText(_translate("daidengy", "Сумма пополнения (не более 999 тыс.)"))
import wall