# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(875, 409)
        MainWindow.setMinimumSize(QtCore.QSize(875, 409))
        MainWindow.setMaximumSize(QtCore.QSize(875, 409))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-family: Neo Sans Pro;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, -20, 876, 361))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 450))
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabWidget.setToolTip("")
        self.tabWidget.setStyleSheet("font-family: Neo Sans Pro;")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_main = QtWidgets.QWidget()
        self.tab_main.setStyleSheet("border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.tab_main.setObjectName("tab_main")
        self.koshelek = QtWidgets.QFrame(self.tab_main)
        self.koshelek.setGeometry(QtCore.QRect(-1, 10, 261, 106))
        self.koshelek.setStyleSheet("background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;")
        self.koshelek.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.koshelek.setFrameShadow(QtWidgets.QFrame.Raised)
        self.koshelek.setObjectName("koshelek")
        self.label = QtWidgets.QLabel(self.koshelek)
        self.label.setGeometry(QtCore.QRect(0, 0, 261, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setStyleSheet("font-size: 20pt;")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.koshelek)
        self.label_4.setGeometry(QtCore.QRect(-15, 40, 71, 61))
        self.label_4.setMaximumSize(QtCore.QSize(900, 900))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/logo/card-dynamic-premium.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.chet = QtWidgets.QLabel(self.koshelek)
        self.chet.setGeometry(QtCore.QRect(50, 50, 141, 30))
        self.chet.setMaximumSize(QtCore.QSize(16777215, 30))
        self.chet.setStyleSheet("font-size: 18pt;\n"
"font-family: Neo Sans Pro;\n"
"\n"
"background-color: none;\n"
"border: none;")
        self.chet.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.chet.setObjectName("chet")
        self.cardvisa = QtWidgets.QLabel(self.koshelek)
        self.cardvisa.setGeometry(QtCore.QRect(50, 80, 146, 25))
        self.cardvisa.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cardvisa.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"color: rgba(100, 100, 100);\n"
"font-size: 12pt;\n"
"font-family: Neo Sans Pro;\n"
"")
        self.cardvisa.setObjectName("cardvisa")
        self.daideneg = QtWidgets.QPushButton(self.koshelek)
        self.daideneg.setGeometry(QtCore.QRect(204, 45, 56, 55))
        self.daideneg.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/logo/daideneg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.daideneg.setIcon(icon1)
        self.daideneg.setIconSize(QtCore.QSize(50, 50))
        self.daideneg.setObjectName("daideneg")
        self.valuta = QtWidgets.QFrame(self.tab_main)
        self.valuta.setGeometry(QtCore.QRect(-1, 120, 261, 221))
        self.valuta.setStyleSheet("font-size: 20pt;\n"
"font-family: Neo Sans Pro;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;")
        self.valuta.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valuta.setFrameShadow(QtWidgets.QFrame.Raised)
        self.valuta.setObjectName("valuta")
        self.label_2 = QtWidgets.QLabel(self.valuta)
        self.label_2.setGeometry(QtCore.QRect(0, -1, 261, 41))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(self.valuta)
        self.label_9.setGeometry(QtCore.QRect(40, 65, 77, 31))
        self.label_9.setStyleSheet("font-size: 20pt;\n"
"font-family: Neo Sans Pro;\n"
"border: none;")
        self.label_9.setObjectName("label_9")
        self.usdbuy = QtWidgets.QLabel(self.valuta)
        self.usdbuy.setGeometry(QtCore.QRect(120, 65, 71, 31))
        self.usdbuy.setStyleSheet("\n"
"font-size: 15pt;\n"
"font-family: Neo Sans Pro;\n"
"border: none;")
        self.usdbuy.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.usdbuy.setObjectName("usdbuy")
        self.label_10 = QtWidgets.QLabel(self.valuta)
        self.label_10.setGeometry(QtCore.QRect(40, 90, 170, 21))
        self.label_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"font-size: 12pt;\n"
"color: rgba(100, 100, 100);")
        self.label_10.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.usdsell = QtWidgets.QLabel(self.valuta)
        self.usdsell.setGeometry(QtCore.QRect(195, 65, 61, 31))
        self.usdsell.setStyleSheet("\n"
"font-size: 15pt;\n"
"font-family: Neo Sans Pro;\n"
"border: none;")
        self.usdsell.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.usdsell.setObjectName("usdsell")
        self.label_39 = QtWidgets.QLabel(self.valuta)
        self.label_39.setGeometry(QtCore.QRect(40, 115, 81, 31))
        self.label_39.setMaximumSize(QtCore.QSize(800, 16777215))
        self.label_39.setStyleSheet("\n"
"font-size: 20pt;\n"
"font-family: Neo Sans Pro;\n"
"border: none;")
        self.label_39.setObjectName("label_39")
        self.eurbuy = QtWidgets.QLabel(self.valuta)
        self.eurbuy.setGeometry(QtCore.QRect(120, 115, 71, 31))
        self.eurbuy.setStyleSheet("\n"
"font-size: 15pt;\n"
"font-family: Neo Sans Pro;\n"
"border: none;")
        self.eurbuy.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.eurbuy.setObjectName("eurbuy")
        self.eursell = QtWidgets.QLabel(self.valuta)
        self.eursell.setGeometry(QtCore.QRect(195, 115, 61, 31))
        self.eursell.setStyleSheet("\n"
"font-size: 15pt;\n"
"font-family: Neo Sans Pro;\n"
"border: none;")
        self.eursell.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.eursell.setObjectName("eursell")
        self.label_40 = QtWidgets.QLabel(self.valuta)
        self.label_40.setGeometry(QtCore.QRect(40, 140, 70, 21))
        self.label_40.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_40.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"color: rgba(180, 180, 180);\n"
"font-size: 12pt;\n"
"font-family: Neo Sans Pro;\n"
"color: rgba(100, 100, 100);")
        self.label_40.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.label_19 = QtWidgets.QLabel(self.valuta)
        self.label_19.setGeometry(QtCore.QRect(40, 165, 77, 31))
        self.label_19.setStyleSheet("\n"
"font-size: 20pt;\n"
"font-family: Neo Sans Pro;\n"
"border: none;")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.valuta)
        self.label_20.setGeometry(QtCore.QRect(40, 195, 131, 21))
        self.label_20.setMaximumSize(QtCore.QSize(999, 16777215))
        self.label_20.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"color: rgba(180, 180, 180);\n"
"font-size: 12pt;\n"
"font-family: Neo Sans Pro;\n"
"color: rgba(100, 100, 100);")
        self.label_20.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.cnysell = QtWidgets.QLabel(self.valuta)
        self.cnysell.setGeometry(QtCore.QRect(195, 165, 61, 31))
        self.cnysell.setStyleSheet("\n"
"font-size: 15pt;\n"
"font-family: Neo Sans Pro;\n"
"border: none;")
        self.cnysell.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.cnysell.setObjectName("cnysell")
        self.cnybuy = QtWidgets.QLabel(self.valuta)
        self.cnybuy.setGeometry(QtCore.QRect(120, 165, 71, 31))
        self.cnybuy.setStyleSheet("\n"
"font-size: 15pt;\n"
"font-family: Neo Sans Pro;\n"
"border: none;")
        self.cnybuy.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.cnybuy.setObjectName("cnybuy")
        self.label_11 = QtWidgets.QLabel(self.valuta)
        self.label_11.setGeometry(QtCore.QRect(5, 40, 111, 21))
        self.label_11.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"font-size: 12pt;\n"
"color: rgba(100, 100, 100);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.valuta)
        self.label_12.setGeometry(QtCore.QRect(115, 40, 71, 21))
        self.label_12.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"font-size: 12pt;\n"
"color: rgba(100, 100, 100);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.valuta)
        self.label_13.setGeometry(QtCore.QRect(190, 40, 71, 21))
        self.label_13.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"font-size: 12pt;\n"
"color: rgba(100, 100, 100);")
        self.label_13.setObjectName("label_13")
        self.label_5 = QtWidgets.QLabel(self.valuta)
        self.label_5.setGeometry(QtCore.QRect(-15, 60, 56, 51))
        self.label_5.setMaximumSize(QtCore.QSize(900, 900))
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/logo/dollar-dynamic-color.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.valuta)
        self.label_8.setGeometry(QtCore.QRect(-15, 110, 56, 51))
        self.label_8.setMaximumSize(QtCore.QSize(900, 900))
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/logo/euro-dynamic-color.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_17 = QtWidgets.QLabel(self.valuta)
        self.label_17.setGeometry(QtCore.QRect(-15, 160, 56, 51))
        self.label_17.setMaximumSize(QtCore.QSize(900, 900))
        self.label_17.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(":/logo/yuan-dynamic-color.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_main)
        self.tableWidget.setGeometry(QtCore.QRect(270, 10, 600, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("background-color: rgba(255, 255, 255); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;\n"
"font: Light")
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(5)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(5)
        self.add_hist = QtWidgets.QPushButton(self.tab_main)
        self.add_hist.setGeometry(QtCore.QRect(270, 305, 601, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_hist.sizePolicy().hasHeightForWidth())
        self.add_hist.setSizePolicy(sizePolicy)
        self.add_hist.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_hist.setStyleSheet("font-size: 17pt;\n"
"font-family: Neo Sans Pro;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/logo/plus-dynamic-premium.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_hist.setIcon(icon2)
        self.add_hist.setIconSize(QtCore.QSize(100, 100))
        self.add_hist.setObjectName("add_hist")
        self.koshelek.raise_()
        self.valuta.raise_()
        self.add_hist.raise_()
        self.tableWidget.raise_()
        self.tabWidget.addTab(self.tab_main, "")
        self.tab_anal = QtWidgets.QWidget()
        self.tab_anal.setObjectName("tab_anal")
        self.per_view = PlotWidget(self.tab_anal)
        self.per_view.setGeometry(QtCore.QRect(5, 50, 601, 291))
        self.per_view.setStyleSheet("font-size: 16pt;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;")
        self.per_view.setObjectName("per_view")
        self.din_but = QtWidgets.QPushButton(self.tab_anal)
        self.din_but.setGeometry(QtCore.QRect(5, 10, 150, 36))
        self.din_but.setStyleSheet("font-size: 16pt;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;")
        self.din_but.setObjectName("din_but")
        self.pev_but = QtWidgets.QPushButton(self.tab_anal)
        self.pev_but.setGeometry(QtCore.QRect(160, 10, 150, 36))
        self.pev_but.setStyleSheet("font-size: 16pt;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;")
        self.pev_but.setObjectName("pev_but")
        self.label_15 = QtWidgets.QLabel(self.tab_anal)
        self.label_15.setGeometry(QtCore.QRect(595, 25, 221, 26))
        self.label_15.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"font-size: 12pt;\n"
"color: rgba(100, 100, 100);")
        self.label_15.setObjectName("label_15")
        self.max_view = QtWidgets.QTableWidget(self.tab_anal)
        self.max_view.setGeometry(QtCore.QRect(610, 50, 256, 291))
        self.max_view.setStyleSheet("font-size: 9pt;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;")
        self.max_view.setObjectName("max_view")
        self.max_view.setColumnCount(0)
        self.max_view.setRowCount(0)
        self.janvar = QtWidgets.QComboBox(self.tab_anal)
        self.janvar.setGeometry(QtCore.QRect(728, 25, 136, 26))
        self.janvar.setStyleSheet("font-size: 16pt;\n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;\n"
"font-size: 12pt;\n"
"color: rgba(100, 100, 100);")
        self.janvar.setObjectName("janvar")
        self.tabWidget.addTab(self.tab_anal, "")
        self.tab_perevod = QtWidgets.QWidget()
        self.tab_perevod.setObjectName("tab_perevod")
        self.SBP = QtWidgets.QFrame(self.tab_perevod)
        self.SBP.setGeometry(QtCore.QRect(5, 70, 286, 216))
        self.SBP.setStyleSheet("border-radius: 7px; \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;")
        self.SBP.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SBP.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SBP.setObjectName("SBP")
        self.sbp_error = QtWidgets.QLabel(self.SBP)
        self.sbp_error.setGeometry(QtCore.QRect(10, 140, 271, 26))
        self.sbp_error.setStyleSheet("color: red;\n"
"font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Neo Sans Pro;")
        self.sbp_error.setText("")
        self.sbp_error.setObjectName("sbp_error")
        self.sbp_contbtn = QtWidgets.QPushButton(self.SBP)
        self.sbp_contbtn.setGeometry(QtCore.QRect(5, 170, 276, 41))
        self.sbp_contbtn.setStyleSheet("font-size: 14pt;\n"
"font-family: Neo Sans Pro Bold;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;\n"
"")
        self.sbp_contbtn.setObjectName("sbp_contbtn")
        self.per_summa = QtWidgets.QLineEdit(self.SBP)
        self.per_summa.setGeometry(QtCore.QRect(5, 95, 276, 41))
        self.per_summa.setStyleSheet("font-family: Neo Sans Pro;\n"
"font-size: 17px")
        self.per_summa.setText("")
        self.per_summa.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.per_summa.setObjectName("per_summa")
        self.per_summalab = QtWidgets.QLabel(self.SBP)
        self.per_summalab.setGeometry(QtCore.QRect(5, 60, 281, 41))
        self.per_summalab.setStyleSheet("font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Neo Sans Pro;")
        self.per_summalab.setObjectName("per_summalab")
        self.per_numtel = QtWidgets.QLineEdit(self.SBP)
        self.per_numtel.setGeometry(QtCore.QRect(5, 25, 276, 41))
        self.per_numtel.setStyleSheet("font-family: Neo Sans Pro;\n"
"font-size: 17px")
        self.per_numtel.setText("")
        self.per_numtel.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.per_numtel.setObjectName("per_numtel")
        self.per_numtelab = QtWidgets.QLabel(self.SBP)
        self.per_numtelab.setGeometry(QtCore.QRect(5, -5, 271, 36))
        self.per_numtelab.setStyleSheet("font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Neo Sans Pro;")
        self.per_numtelab.setObjectName("per_numtelab")
        self.blago = QtWidgets.QComboBox(self.SBP)
        self.blago.setGeometry(QtCore.QRect(5, 215, 276, 41))
        self.blago.setStyleSheet("font-size: 11pt;\n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;\n"
"font: Bold;")
        self.blago.setObjectName("blago")
        self.blago.addItem("")
        self.blago.addItem("")
        self.blago.addItem("")
        self.blago.addItem("")
        self.blago.addItem("")
        self.blago.addItem("")
        self.perevodkomy = QtWidgets.QComboBox(self.tab_perevod)
        self.perevodkomy.setGeometry(QtCore.QRect(5, 30, 286, 36))
        self.perevodkomy.setStyleSheet("font-size: 11pt;\n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;\n"
"font: Bold;")
        self.perevodkomy.setObjectName("perevodkomy")
        self.perevodkomy.addItem("")
        self.perevodkomy.setItemText(0, "")
        self.perevodkomy.addItem("")
        self.perevodkomy.addItem("")
        self.perevodkomy.addItem("")
        self.perevodkomy.addItem("")
        self.label_14 = QtWidgets.QLabel(self.tab_perevod)
        self.label_14.setGeometry(QtCore.QRect(5, 0, 271, 41))
        self.label_14.setStyleSheet("font-size: 11pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_14.setObjectName("label_14")
        self.perevod_wid = QtWidgets.QTableWidget(self.tab_perevod)
        self.perevod_wid.setGeometry(QtCore.QRect(305, 30, 561, 311))
        self.perevod_wid.setStyleSheet("background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;")
        self.perevod_wid.setObjectName("perevod_wid")
        self.perevod_wid.setColumnCount(0)
        self.perevod_wid.setRowCount(0)
        self.label_18 = QtWidgets.QLabel(self.tab_perevod)
        self.label_18.setGeometry(QtCore.QRect(305, 0, 271, 41))
        self.label_18.setStyleSheet("font-size: 11pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_18.setObjectName("label_18")
        self.tabWidget.addTab(self.tab_perevod, "")
        self.tab_user = QtWidgets.QWidget()
        self.tab_user.setObjectName("tab_user")
        self.frame_123 = QtWidgets.QFrame(self.tab_user)
        self.frame_123.setGeometry(QtCore.QRect(5, 10, 896, 331))
        self.frame_123.setStyleSheet("border-radius: 7px; \n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"font-size: 17px;\n"
"background-color: none;\n"
"font-family: Neo Sans;")
        self.frame_123.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_123.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_123.setObjectName("frame_123")
        self.label_6 = QtWidgets.QLabel(self.frame_123)
        self.label_6.setGeometry(QtCore.QRect(5, 0, 251, 40))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_6.setStyleSheet("font-size: 24pt;\n"
"font-family: Neo Sans Pro;\n"
"border: none;\n"
"background: none;")
        self.label_6.setObjectName("label_6")
        self.sexicon = QtWidgets.QLabel(self.frame_123)
        self.sexicon.setGeometry(QtCore.QRect(-20, 40, 101, 101))
        self.sexicon.setMaximumSize(QtCore.QSize(900, 900))
        self.sexicon.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);")
        self.sexicon.setText("")
        self.sexicon.setPixmap(QtGui.QPixmap(":/logo/boy-dynamic-color.png"))
        self.sexicon.setScaledContents(True)
        self.sexicon.setObjectName("sexicon")
        self.prof_name = QtWidgets.QLabel(self.frame_123)
        self.prof_name.setGeometry(QtCore.QRect(85, 65, 211, 46))
        self.prof_name.setMaximumSize(QtCore.QSize(16777215, 999))
        self.prof_name.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"font-size: 18pt;\n"
"font-family: Neo Sans Pro;\n"
"")
        self.prof_name.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignJustify)
        self.prof_name.setObjectName("prof_name")
        self.cardvisa_3 = QtWidgets.QLabel(self.frame_123)
        self.cardvisa_3.setGeometry(QtCore.QRect(320, 75, 201, 25))
        self.cardvisa_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cardvisa_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"color: rgba(100, 100, 100);\n"
"font-size: 12pt;\n"
"font-family: Neo Sans Pro;\n"
"")
        self.cardvisa_3.setObjectName("cardvisa_3")
        self.telefon_label = QtWidgets.QLineEdit(self.frame_123)
        self.telefon_label.setGeometry(QtCore.QRect(320, 105, 261, 31))
        self.telefon_label.setStyleSheet("font-size: 17px;")
        self.telefon_label.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.telefon_label.setObjectName("telefon_label")
        self.password_label = QtWidgets.QLineEdit(self.frame_123)
        self.password_label.setGeometry(QtCore.QRect(0, 230, 311, 31))
        self.password_label.setStyleSheet("font-size: 17px;")
        self.password_label.setText("")
        self.password_label.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.password_label.setObjectName("password_label")
        self.cardvisa_5 = QtWidgets.QLabel(self.frame_123)
        self.cardvisa_5.setGeometry(QtCore.QRect(0, 200, 201, 25))
        self.cardvisa_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cardvisa_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"color: rgba(100, 100, 100);\n"
"font-size: 12pt;\n"
"font-family: Neo Sans Pro;\n"
"")
        self.cardvisa_5.setObjectName("cardvisa_5")
        self.sec_password_label = QtWidgets.QLineEdit(self.frame_123)
        self.sec_password_label.setGeometry(QtCore.QRect(0, 295, 311, 31))
        self.sec_password_label.setStyleSheet("font-size: 17px;")
        self.sec_password_label.setText("")
        self.sec_password_label.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.sec_password_label.setObjectName("sec_password_label")
        self.cardvisa_6 = QtWidgets.QLabel(self.frame_123)
        self.cardvisa_6.setGeometry(QtCore.QRect(5, 265, 201, 25))
        self.cardvisa_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cardvisa_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"color: rgba(100, 100, 100);\n"
"font-size: 12pt;\n"
"font-family: Neo Sans Pro;\n"
"")
        self.cardvisa_6.setObjectName("cardvisa_6")
        self.error_label = QtWidgets.QLabel(self.frame_123)
        self.error_label.setGeometry(QtCore.QRect(325, 265, 251, 26))
        self.error_label.setStyleSheet("color: red;\n"
"font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Neo Sans Pro;")
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.smenit = QtWidgets.QPushButton(self.frame_123)
        self.smenit.setGeometry(QtCore.QRect(320, 295, 261, 31))
        self.smenit.setStyleSheet("\n"
"font-size: 15pt;\n"
"font-family: Neo Sans Pro;\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/logo/pencil-dynamic-premium.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.smenit.setIcon(icon3)
        self.smenit.setIconSize(QtCore.QSize(30, 30))
        self.smenit.setObjectName("smenit")
        self.cardvisa_7 = QtWidgets.QLabel(self.frame_123)
        self.cardvisa_7.setGeometry(QtCore.QRect(320, 10, 201, 25))
        self.cardvisa_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cardvisa_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"color: rgba(100, 100, 100);\n"
"font-size: 12pt;\n"
"font-family: Neo Sans Pro;\n"
"")
        self.cardvisa_7.setObjectName("cardvisa_7")
        self.name_label = QtWidgets.QLineEdit(self.frame_123)
        self.name_label.setGeometry(QtCore.QRect(320, 40, 261, 31))
        self.name_label.setStyleSheet("font-size: 17px;")
        self.name_label.setText("")
        self.name_label.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.name_label.setObjectName("name_label")
        self.cardvisa_12 = QtWidgets.QLabel(self.frame_123)
        self.cardvisa_12.setGeometry(QtCore.QRect(320, 140, 201, 25))
        self.cardvisa_12.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cardvisa_12.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"color: rgba(100, 100, 100);\n"
"font-size: 12pt;\n"
"font-family: Neo Sans Pro;\n"
"")
        self.cardvisa_12.setObjectName("cardvisa_12")
        self.visa_box = QtWidgets.QComboBox(self.frame_123)
        self.visa_box.setGeometry(QtCore.QRect(320, 165, 261, 31))
        self.visa_box.setStyleSheet("font-size: 17px;\n"
"background-color: none;\n"
"font-family: Neo Sans;")
        self.visa_box.setObjectName("visa_box")
        self.visa_box.addItem("")
        self.visa_box.addItem("")
        self.visa_box.addItem("")
        self.visa_box.addItem("")
        self.cardvisa_14 = QtWidgets.QLabel(self.frame_123)
        self.cardvisa_14.setGeometry(QtCore.QRect(0, 140, 256, 25))
        self.cardvisa_14.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cardvisa_14.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"color: rgba(100, 100, 100);\n"
"font-size: 12pt;\n"
"font-family: Neo Sans Pro;\n"
"")
        self.cardvisa_14.setObjectName("cardvisa_14")
        self.cardnum_profil = QtWidgets.QLineEdit(self.frame_123)
        self.cardnum_profil.setGeometry(QtCore.QRect(0, 165, 311, 31))
        self.cardnum_profil.setStyleSheet("font-size: 17px;")
        self.cardnum_profil.setText("")
        self.cardnum_profil.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cardnum_profil.setObjectName("cardnum_profil")
        self.vihod = QtWidgets.QPushButton(self.frame_123)
        self.vihod.setGeometry(QtCore.QRect(605, 0, 111, 331))
        self.vihod.setStyleSheet("\n"
"font-size: 15pt;\n"
"font-family: Neo Sans Pro;\n"
"")
        self.vihod.setIconSize(QtCore.QSize(50, 50))
        self.vihod.setObjectName("vihod")
        self.label_3 = QtWidgets.QLabel(self.frame_123)
        self.label_3.setGeometry(QtCore.QRect(545, 130, 210, 210))
        self.label_3.setStyleSheet("border-color: none;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/logo/key-dynamic-premium.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.frame_123)
        self.label_7.setGeometry(QtCore.QRect(716, 1, 156, 329))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: none;\n"
"")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/logo/lisa.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_21 = QtWidgets.QLabel(self.frame_123)
        self.label_21.setGeometry(QtCore.QRect(5, 5, 601, 321))
        self.label_21.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: none;")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.cardvisa_13 = QtWidgets.QLabel(self.frame_123)
        self.cardvisa_13.setGeometry(QtCore.QRect(320, 200, 201, 25))
        self.cardvisa_13.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cardvisa_13.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"color: rgba(100, 100, 100);\n"
"font-size: 12pt;\n"
"font-family: Neo Sans Pro;\n"
"")
        self.cardvisa_13.setObjectName("cardvisa_13")
        self.sex_box = QtWidgets.QComboBox(self.frame_123)
        self.sex_box.setGeometry(QtCore.QRect(320, 230, 261, 26))
        self.sex_box.setStyleSheet("")
        self.sex_box.setObjectName("sex_box")
        self.sex_box.addItem("")
        self.sex_box.addItem("")
        self.sex_box.addItem("")
        self.horosh = QtWidgets.QLabel(self.frame_123)
        self.horosh.setGeometry(QtCore.QRect(325, 265, 251, 26))
        self.horosh.setMaximumSize(QtCore.QSize(16777215, 999))
        self.horosh.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"font-size: 8pt;\n"
"font-family: Neo Sans Pro;\n"
"")
        self.horosh.setText("")
        self.horosh.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignJustify)
        self.horosh.setObjectName("horosh")
        self.label_3.raise_()
        self.label_21.raise_()
        self.label_6.raise_()
        self.sexicon.raise_()
        self.prof_name.raise_()
        self.cardvisa_3.raise_()
        self.password_label.raise_()
        self.cardvisa_5.raise_()
        self.sec_password_label.raise_()
        self.cardvisa_6.raise_()
        self.cardvisa_7.raise_()
        self.cardvisa_12.raise_()
        self.cardvisa_14.raise_()
        self.cardnum_profil.raise_()
        self.vihod.raise_()
        self.name_label.raise_()
        self.telefon_label.raise_()
        self.smenit.raise_()
        self.visa_box.raise_()
        self.error_label.raise_()
        self.cardvisa_13.raise_()
        self.sex_box.raise_()
        self.horosh.raise_()
        self.label_7.raise_()
        self.tabWidget.addTab(self.tab_user, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(5, 340, 866, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.homebut = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homebut.sizePolicy().hasHeightForWidth())
        self.homebut.setSizePolicy(sizePolicy)
        self.homebut.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.homebut.setStyleSheet("font-size: 23pt;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,150);\n"
"border-radius: 7px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/logo/wallet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homebut.setIcon(icon4)
        self.homebut.setIconSize(QtCore.QSize(50, 50))
        self.homebut.setObjectName("homebut")
        self.horizontalLayout.addWidget(self.homebut)
        self.perevodbut = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perevodbut.sizePolicy().hasHeightForWidth())
        self.perevodbut.setSizePolicy(sizePolicy)
        self.perevodbut.setStyleSheet("font-size: 23pt;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,60);\n"
"border-radius: 7px;")
        self.perevodbut.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/logo/play-dynamic-premium.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.perevodbut.setIcon(icon5)
        self.perevodbut.setIconSize(QtCore.QSize(50, 50))
        self.perevodbut.setObjectName("perevodbut")
        self.horizontalLayout.addWidget(self.perevodbut)
        self.analizbut = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analizbut.sizePolicy().hasHeightForWidth())
        self.analizbut.setSizePolicy(sizePolicy)
        self.analizbut.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.analizbut.setStyleSheet("font-size: 23pt;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,60);\n"
"border-radius: 7px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/logo/calculator-dynamic-premium.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.analizbut.setIcon(icon6)
        self.analizbut.setIconSize(QtCore.QSize(50, 50))
        self.analizbut.setObjectName("analizbut")
        self.horizontalLayout.addWidget(self.analizbut)
        self.userbut = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userbut.sizePolicy().hasHeightForWidth())
        self.userbut.setSizePolicy(sizePolicy)
        self.userbut.setStyleSheet("font-size: 23pt;\n"
"font-family: Neo Sans Pro;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,60);\n"
"border-radius: 7px;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/logo/crown-dynamic-premium.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userbut.setIcon(icon7)
        self.userbut.setIconSize(QtCore.QSize(50, 50))
        self.userbut.setObjectName("userbut")
        self.horizontalLayout.addWidget(self.userbut)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FOXBANK"))
        self.label.setText(_translate("MainWindow", "Кошелёк"))
        self.chet.setText(_translate("MainWindow", "0$"))
        self.cardvisa.setText(_translate("MainWindow", "Visa Classik ••0000"))
        self.label_2.setText(_translate("MainWindow", "Валюта"))
        self.label_9.setText(_translate("MainWindow", "USD"))
        self.usdbuy.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "Доллар США"))
        self.usdsell.setText(_translate("MainWindow", "0"))
        self.label_39.setText(_translate("MainWindow", "EUR"))
        self.eurbuy.setText(_translate("MainWindow", "0"))
        self.eursell.setText(_translate("MainWindow", "0"))
        self.label_40.setText(_translate("MainWindow", "Евро"))
        self.label_19.setText(_translate("MainWindow", "CNY"))
        self.label_20.setText(_translate("MainWindow", "Китайский юань"))
        self.cnysell.setText(_translate("MainWindow", "0"))
        self.cnybuy.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Валюта"))
        self.label_12.setText(_translate("MainWindow", "Купить"))
        self.label_13.setText(_translate("MainWindow", "Продать"))
        self.add_hist.setText(_translate("MainWindow", "ДОБАВИТЬ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main), _translate("MainWindow", "Главная"))
        self.din_but.setText(_translate("MainWindow", "Динамика"))
        self.pev_but.setText(_translate("MainWindow", "Переводы"))
        self.label_15.setText(_translate("MainWindow", "Данные за числа"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_anal), _translate("MainWindow", "Page"))
        self.sbp_contbtn.setText(_translate("MainWindow", "ПЕРЕВЕСТИ"))
        self.per_summalab.setText(_translate("MainWindow", "Сумма перевода"))
        self.per_numtelab.setText(_translate("MainWindow", "Номер телефона:"))
        self.blago.setItemText(0, _translate("MainWindow", "Вера"))
        self.blago.setItemText(1, _translate("MainWindow", "Альцрус"))
        self.blago.setItemText(2, _translate("MainWindow", "Подари жизнь"))
        self.blago.setItemText(3, _translate("MainWindow", "Дом с маяком"))
        self.blago.setItemText(4, _translate("MainWindow", "Новый дом"))
        self.blago.setItemText(5, _translate("MainWindow", "Детский мир"))
        self.perevodkomy.setItemText(1, _translate("MainWindow", "СБП"))
        self.perevodkomy.setItemText(2, _translate("MainWindow", "Мобильная связь"))
        self.perevodkomy.setItemText(3, _translate("MainWindow", "Транспортная карта"))
        self.perevodkomy.setItemText(4, _translate("MainWindow", "Благотворительность"))
        self.label_14.setText(_translate("MainWindow", "Кому:"))
        self.label_18.setText(_translate("MainWindow", "Последние переводы:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_perevod), _translate("MainWindow", "Платежи и переводы"))
        self.label_6.setText(_translate("MainWindow", "Профиль"))
        self.prof_name.setText(_translate("MainWindow", "ахахах"))
        self.cardvisa_3.setText(_translate("MainWindow", "Телефон"))
        self.telefon_label.setInputMask(_translate("MainWindow", "+79999999999"))
        self.telefon_label.setText(_translate("MainWindow", "+7"))
        self.cardvisa_5.setText(_translate("MainWindow", "Пароль:"))
        self.cardvisa_6.setText(_translate("MainWindow", "Пароль повторно:"))
        self.smenit.setText(_translate("MainWindow", "Сменить"))
        self.cardvisa_7.setText(_translate("MainWindow", "Имя"))
        self.cardvisa_12.setText(_translate("MainWindow", "Платежная система"))
        self.visa_box.setItemText(0, _translate("MainWindow", "Visa Classic"))
        self.visa_box.setItemText(1, _translate("MainWindow", "MasterCard"))
        self.visa_box.setItemText(2, _translate("MainWindow", "Мир"))
        self.visa_box.setItemText(3, _translate("MainWindow", "UnionPay"))
        self.cardvisa_14.setText(_translate("MainWindow", "Номер карты"))
        self.cardnum_profil.setInputMask(_translate("MainWindow", "9999999999999999"))
        self.vihod.setText(_translate("MainWindow", "Выход"))
        self.cardvisa_13.setText(_translate("MainWindow", "Пол"))
        self.sex_box.setItemText(0, _translate("MainWindow", "Мужской"))
        self.sex_box.setItemText(1, _translate("MainWindow", "Не указывать"))
        self.sex_box.setItemText(2, _translate("MainWindow", "Женский"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_user), _translate("MainWindow", "Page"))
        self.homebut.setText(_translate("MainWindow", "ГЛАВНАЯ"))
        self.perevodbut.setText(_translate("MainWindow", "ПЕРЕВОДЫ"))
        self.analizbut.setText(_translate("MainWindow", "ДИНАМИКА"))
        self.userbut.setText(_translate("MainWindow", "ПРОФИЛЬ"))
from pyqtgraph import PlotWidget
