# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suc_perevod_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(446, 239)
        Dialog.setStyleSheet("")
        self.sucperevod = QtWidgets.QFrame(Dialog)
        self.sucperevod.setGeometry(QtCore.QRect(5, 0, 441, 241))
        self.sucperevod.setStyleSheet("background-color: rgba(255, 255, 255, 30); \n"
"border: 2px solid rgba(255,255,255,40);\n"
"border-radius: 7px; \n"
"font-family: Neo Sans Pro;")
        self.sucperevod.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sucperevod.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sucperevod.setObjectName("sucperevod")
        self.countbtn = QtWidgets.QPushButton(self.sucperevod)
        self.countbtn.setGeometry(QtCore.QRect(0, 195, 436, 41))
        self.countbtn.setStyleSheet("background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 7px;\n"
"font-size: 24pt;\n"
"font: Medium;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;")
        self.countbtn.setObjectName("countbtn")
        self.frame_5 = QtWidgets.QFrame(self.sucperevod)
        self.frame_5.setGeometry(QtCore.QRect(0, 50, 436, 141))
        self.frame_5.setStyleSheet("font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Vag World;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(5, 5, 146, 41))
        self.label_16.setStyleSheet("font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Vag World;")
        self.label_16.setObjectName("label_16")
        self.dkomy = QtWidgets.QLabel(self.frame_5)
        self.dkomy.setGeometry(QtCore.QRect(140, 5, 291, 41))
        self.dkomy.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.dkomy.setStyleSheet("font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Vag World;")
        self.dkomy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dkomy.setObjectName("dkomy")
        self.dskolko = QtWidgets.QLabel(self.frame_5)
        self.dskolko.setGeometry(QtCore.QRect(140, 50, 291, 41))
        self.dskolko.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.dskolko.setStyleSheet("font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Vag World;")
        self.dskolko.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dskolko.setObjectName("dskolko")
        self.label_21 = QtWidgets.QLabel(self.frame_5)
        self.label_21.setGeometry(QtCore.QRect(5, 50, 146, 41))
        self.label_21.setStyleSheet("font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Vag World;")
        self.label_21.setObjectName("label_21")
        self.dostalos = QtWidgets.QLabel(self.frame_5)
        self.dostalos.setGeometry(QtCore.QRect(135, 95, 296, 41))
        self.dostalos.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.dostalos.setStyleSheet("font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Vag World;")
        self.dostalos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dostalos.setObjectName("dostalos")
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        self.label_23.setGeometry(QtCore.QRect(5, 95, 146, 41))
        self.label_23.setStyleSheet("font-size: 11pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-family: Vag World;")
        self.label_23.setObjectName("label_23")
        self.suc = QtWidgets.QPushButton(self.sucperevod)
        self.suc.setGeometry(QtCore.QRect(0, 5, 436, 41))
        self.suc.setStyleSheet("background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 7px;\n"
"font-size: 20pt;\n"
"font-family: Neo Sans Pro;\n"
"font: Medium;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(0,0,0,40);\n"
"border-radius: 7px;")
        self.suc.setObjectName("suc")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Успешно!"))
        self.countbtn.setText(_translate("Dialog", "ОК"))
        self.label_16.setText(_translate("Dialog", "Кому:"))
        self.dkomy.setText(_translate("Dialog", "кому-то"))
        self.dskolko.setText(_translate("Dialog", "сколько-то"))
        self.label_21.setText(_translate("Dialog", "Сколько"))
        self.dostalos.setText(_translate("Dialog", "столько-то"))
        self.label_23.setText(_translate("Dialog", "Оставшийся счёт"))
        self.suc.setText(_translate("Dialog", "Успешно!"))
import wall